version: '4.1'

networks:
  database:
    driver: bridge
  voicevox:
    driver: bridge

services:
  discord-bot:
    build: ./
    tty: true
    volumes:
      - ./bot/:/workspace/discord-bot
      - node-modules:/workspace/discord-bot/node_modules
    working_dir: /workspace/discord-bot
    networks:
      - database
      - voicevox

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: discord
      POSTGRES_DB: discord
    networks:
      - database

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50022"
    networks:
      - voicevox

volumes:
  node-modules:
  postgres-data:
