name: CD

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # - name: Set up buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Stop Docker Compose
        run: docker compose down

      - name: Build and Up
        run: docker compose up -d --build

      - name: Deploy-command
        run: docker compose exec discord-bot npm run deploy-command

      - name: Build
        run: docker compose exec discord-bot npm run build

      - name: tmux
        run: tmux a && docker compose exec discord-bot npm run start
